### ISSUE TITLE
AWS基盤構築

### ISSUE THREAD

**Issue by suzuki84g** [IkaProduction/RefreshList_server#3]
ログインからネットワークを切るところまで

**Comment by suzuki84g** [comment]
@otera05 教えて下さいーーーーー。
概ねVPCの設定が終わった辺りで、リージョンがオハイオだった事に気付いてしまった。
これ東京にまるごと引っ越しとか出来るんですかorする必要ありますか…？
手動で構築し直しが良い…？

**Comment by otera05** [comment]
まるごと引っ越せないので東京リージョンで作り直しですね。
作り直したらオハイオリージョンのVPCはまるごと削除です。
どんまいです。

**Comment by suzuki84g** [comment]
OKありがとう、要領は分かったのでやっていきます。

**Comment by suzuki84g** [comment]
VPCは東京リージョンで終わったので一旦Doneに。
DBとかEC2は引き続き検証環境用に立てたりしていく感じで。

**Comment by suzuki84g** [comment]
最後にやって充分間に合うことが分かったのでクローズします。
