### ISSUE TITLE
ローカル開発環境とgithub

### ISSUE THREAD

**Issue by suzuki84g** [IkaProduction/RefreshList_server#7]
githubからソースコードをclone、Pull、Push出来るように連携する。

**Comment by suzuki84g** [comment]
自分のアカウント（`suzuki84g`）以外のgithub空間を殆ど扱った事が無いのでちょっと確認させて下さい。
基本的に、他の人のgithubのコードをどうこうしたいときって、

1. forkして自分のgithubのRepositoryに持ってくる
2. ローカルにcloneしてブランチ切るとかコード書くとかしてなんか色々やる
3. 自分のRepositoryを更新する
4. fork元に対してPull Requestする
5. （内容が精査された後に妥当であれば）mergeされる

だと思ってます。
**今回はforkって必要ですか？**
直でIkaProのRepository（ここではserver）を引っ張ってきても、Organizationのメンバーに全員入ってるから問題ない？

**Comment by otera05** [comment]
基本的に fork は必要ないと思います。
fork する場合は何かオープンソースのバグとか見つけて修正する場合とかにするイメージ。
まぁ fork すれば大元のリポジトリ汚す恐れがないのでより安全ではあります。

Ika Pro は Github Flow に則って開発するのがいいんじゃないかな。

https://qiita.com/tlta-bkhn/items/fc485a66dbe48ec3b919#github-flow%E3%81%AE%E8%AA%AC%E6%98%8E

- `develop` ブランチを切る
- 各々が `develop` ブランチをローカルに clone してそこから開発用のブランチを切って開発する
- `develop` ブランチに対して Pull Request を送る
- レビュー後、問題なければ  `develop` ブランチにマージ
- リリースのタイミングで `develop` ブランチから `master` ブランチにマージ

こんな感じでいいんじゃないかな。
というか、弊社はリリースするまではこの流れで開発してました。

**Comment by suzuki84g** [comment]
了解しました。
取り敢えず`develop`切ります。
